name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  call-reusable-test:
    uses: ./.github/workflows/reusable_test.yml
    with:
      python-version: '3.10'